"use client";

import type React from "react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/constructor-x/app-shell";
import { CustomDropdown } from "@/components/constructor-x/custom-controls";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CalendarDays, Check, ChevronDown, ChevronRight, Clock3, Download, History, MoreHorizontal, Plus, Search, SlidersHorizontal, Users2, WalletCards } from "lucide-react";

const PEOPLE = [
  { id: "u-01", initials: "TV", name: "Trần Văn Minh", role: "Project Manager", department: "Delivery", level: "L3", status: "Active", rate: 520000, effective: "01/07/2026", logs: 142, color: "#2563eb" },
  { id: "u-02", initials: "LN", name: "Lê Ngọc Anh", role: "Business Analyst", department: "Consulting", level: "L2", status: "Active", rate: 410000, effective: "01/05/2026", logs: 128, color: "#7c3aed" },
  { id: "u-03", initials: "PT", name: "Phạm Thanh Tùng", role: "Developer", department: "Engineering", level: "L3", status: "Active", rate: 460000, effective: "01/07/2026", logs: 168, color: "#059669" },
  { id: "u-04", initials: "HT", name: "Hoàng Thu Hà", role: "QA Engineer", department: "Quality", level: "L2", status: "Active", rate: 360000, effective: "01/01/2026", logs: 96, color: "#d97706" },
  { id: "u-05", initials: "ĐN", name: "Đỗ Nhật Nam", role: "Support", department: "Customer Success", level: "L1", status: "On leave", rate: 280000, effective: "15/03/2026", logs: 72, color: "#db2777" }
];

const PROJECTS = [
  { code: "P-9001", name: "CRM cho Khách hàng A", client: "Khách hàng A", status: "Active", plan: 4800, logwork: 3280, pnl: 3120, revenue: 1680000000, expenses: 430000000, pending: 160 },
  { code: "P-9002", name: "Portal đối tác B", client: "Khách hàng B", status: "In Review", plan: 2240, logwork: 1940, pnl: 1880, revenue: 920000000, expenses: 286000000, pending: 60 },
  { code: "P-9003", name: "Tích hợp ERP nội bộ", client: "Nội bộ", status: "On Hold", plan: 1200, logwork: 620, pnl: 0, revenue: 0, expenses: 84000000, pending: 620 }
];

const EXPENSE_GROUPS = [
  { label: "BD", share: 0.08 },
  { label: "PM", share: 0.18 },
  { label: "Delivery / DX", share: 0.54 },
  { label: "AI / Công cụ", share: 0.08 },
  { label: "Overhead", share: 0.07 },
  { label: "Khác", share: 0.05 }
];

function Avatar({ person, large = false }: { person: typeof PEOPLE[number]; large?: boolean }) {
  return <span className={`inline-flex shrink-0 items-center justify-center rounded-full font-bold text-white ${large ? "h-11 w-11 text-sm" : "h-8 w-8 text-[10px]"}`} style={{ backgroundColor: person.color }}>{person.initials}</span>;
}

function Status({ children, tone = "success" }: { children: React.ReactNode; tone?: "success" | "warning" | "neutral" | "info" | "danger" }) {
  const styles = { success: "bg-emerald-50 text-emerald-700", warning: "bg-amber-50 text-amber-700", neutral: "bg-slate-100 text-slate-600", info: "bg-blue-50 text-blue-700", danger: "bg-red-50 text-red-700" };
  return <span className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[10px] font-semibold ${styles[tone]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{children}</span>;
}

function Metric({ label, value, hint, icon: Icon, tone = "blue" }: { label: string; value: string; hint: string; icon: typeof Users2; tone?: "blue" | "green" | "amber" | "purple" }) {
  const colors = { blue: "bg-blue-50 text-blue-600", green: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", purple: "bg-violet-50 text-violet-600" };
  return <article className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start justify-between"><span className="text-[11px] font-semibold text-muted-foreground">{label}</span><span className={`rounded-lg p-2 ${colors[tone]}`}><Icon className="h-4 w-4" /></span></div><strong className="mt-3 block text-2xl font-extrabold tracking-tight text-foreground">{value}</strong><span className="mt-1 block text-[11px] text-muted-foreground">{hint}</span></article>;
}

function Toolbar({ children, onSearch }: { children?: React.ReactNode; onSearch?: (value: string) => void }) {
  return <div className="flex flex-col gap-3 rounded-xl border border-border bg-card p-3 shadow-sm md:flex-row md:items-center"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input aria-label="Tìm kiếm" onChange={(e) => onSearch?.(e.target.value)} placeholder="Tìm theo tên, User ID, phòng ban..." className="h-10 w-full rounded-lg border border-border bg-muted/30 pl-9 pr-3 text-xs outline-none focus:border-primary" /></div>{children}<button type="button" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-border px-3 text-xs font-semibold text-muted-foreground hover:bg-muted"><SlidersHorizontal className="h-3.5 w-3.5" /> Bộ lọc</button></div>;
}

export function HrProfileWorkbench() {
  const [query, setQuery] = useState("");
  const [departmentFilter, setDepartmentFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [selected, setSelected] = useState(PEOPLE[0]);
  const [showRate, setShowRate] = useState(false);
  const filtered = useMemo(() => PEOPLE.filter((p) => `${p.name} ${p.role} ${p.department} ${p.id}`.toLowerCase().includes(query.toLowerCase()) && (departmentFilter === "all" || p.department === departmentFilter) && (statusFilter === "all" || (statusFilter === "active" ? p.status === "Active" : p.status === "On leave"))), [query, departmentFilter, statusFilter]);
  return <AppShell activeRoute="/people" title="Hồ sơ nhân sự"><main className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-[1480px] space-y-4">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-primary">CHI PHÍ NGUỒN LỰC · PILOT</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Hồ sơ nhân sự</h1><p className="mt-1 text-xs text-muted-foreground">Quản lý User ID, Level, trạng thái và Cost Rate theo ngày hiệu lực.</p></div><button onClick={() => setShowRate(true)} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-xs font-bold text-white shadow-sm hover:bg-blue-700"><Plus className="h-4 w-4" /> Thêm Cost Rate</button></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Tổng nhân sự" value="24" hint="18 đang active" icon={Users2} /><Metric label="Cost Rate đã cấu hình" value="22 / 24" hint="2 hồ sơ cần xử lý" icon={WalletCards} tone="green" /><Metric label="Thay đổi trong kỳ" value="3" hint="có lịch sử hiệu lực" icon={History} tone="purple" /><Metric label="Chưa map User ID" value="2" hint="không được dùng cho P&L" icon={AlertTriangle} tone="amber" /></div>
    <Toolbar onSearch={setQuery}><CustomDropdown ariaLabel="Phòng ban" options={[{ value: "all", label: "Tất cả phòng ban" }, ...Array.from(new Set(PEOPLE.map((p) => p.department))).map((d) => ({ value: d, label: d }))]} value={departmentFilter} onChange={setDepartmentFilter} /><CustomDropdown ariaLabel="Trạng thái" options={[{ value: "all", label: "Tất cả trạng thái" }, { value: "active", label: "Active" }, { value: "leave", label: "On leave" }]} value={statusFilter} onChange={setStatusFilter} /></Toolbar>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div><h2 className="text-sm font-bold">Danh sách hồ sơ</h2><p className="text-[11px] text-muted-foreground">{filtered.length} hồ sơ trong phạm vi được xem</p></div><button className="inline-flex items-center gap-1 text-xs font-semibold text-primary"><Download className="h-3.5 w-3.5" /> Xuất danh sách</button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Nhân sự / User ID</th><th className="px-3 py-3">Phòng ban · Vai trò</th><th className="px-3 py-3">Level</th><th className="px-3 py-3">Trạng thái</th><th className="px-3 py-3">Cost Rate / giờ</th><th className="px-3 py-3">Hiệu lực từ</th><th /></tr></thead><tbody className="divide-y divide-border">{filtered.map((person) => <tr key={person.id} onClick={() => setSelected(person)} className={`cursor-pointer transition-colors hover:bg-blue-50/40 ${selected.id === person.id ? "bg-blue-50/60" : ""}`}><td className="px-4 py-3"><div className="flex items-center gap-2.5"><Avatar person={person} /><div><div className="font-semibold text-foreground">{person.name}</div><div className="font-mono text-[10px] text-muted-foreground">{person.id} · {person.logs} time logs</div></div></div></td><td className="px-3 py-3"><div className="font-medium">{person.department}</div><div className="text-[10px] text-muted-foreground">{person.role}</div></td><td className="px-3 py-3"><span className="rounded-md bg-violet-50 px-2 py-1 text-[10px] font-bold text-violet-700">{person.level}</span></td><td className="px-3 py-3"><Status tone={person.status === "Active" ? "success" : "warning"}>{person.status}</Status></td><td className="px-3 py-3 font-mono font-semibold tabular-nums">{person.rate.toLocaleString("vi-VN")} ₫</td><td className="px-3 py-3 text-muted-foreground">{person.effective}</td><td className="px-3 py-3"><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></td></tr>)}</tbody></table></div></section>
      <aside className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Hồ sơ đang chọn</span><button className="text-xs font-semibold text-primary">Chỉnh sửa</button></div><div className="mt-4 flex items-center gap-3"><Avatar person={selected} large /><div><h2 className="text-base font-bold">{selected.name}</h2><p className="text-xs text-muted-foreground">{selected.role} · {selected.department}</p><Status>{selected.status}</Status></div></div><dl className="mt-5 divide-y divide-border text-xs"><div className="flex justify-between py-3"><dt className="text-muted-foreground">User ID</dt><dd className="font-mono font-semibold">{selected.id}</dd></div><div className="flex justify-between py-3"><dt className="text-muted-foreground">Level</dt><dd className="font-semibold">{selected.level}</dd></div><div className="flex justify-between py-3"><dt className="text-muted-foreground">Cost Rate hiện tại</dt><dd className="font-mono font-semibold">{selected.rate.toLocaleString("vi-VN")} ₫/giờ</dd></div><div className="flex justify-between py-3"><dt className="text-muted-foreground">Ngày hiệu lực</dt><dd className="font-semibold">{selected.effective}</dd></div></dl><button onClick={() => setShowRate(true)} className="mt-3 flex w-full items-center justify-between rounded-lg border border-border px-3 py-2.5 text-xs font-semibold hover:bg-muted"><span className="flex items-center gap-2"><History className="h-3.5 w-3.5 text-primary" /> Xem lịch sử Cost Rate</span><ChevronRight className="h-3.5 w-3.5" /></button><div className="mt-4 rounded-lg bg-amber-50 p-3 text-[11px] leading-relaxed text-amber-800"><div className="flex items-center gap-1.5 font-bold"><AlertTriangle className="h-3.5 w-3.5" /> Quy tắc hiệu lực</div><p className="mt-1">Logwork lấy Cost Rate theo đúng ngày ghi giờ. Không tự dùng mức gần nhất nếu thiếu bản ghi.</p></div></aside></div>
    {showRate ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-base font-bold">Lịch sử Cost Rate · {selected.name}</h2><p className="mt-1 text-xs text-muted-foreground">Các mức được dùng khi tính chi phí theo ngày hiệu lực.</p></div><button onClick={() => setShowRate(false)} className="rounded-lg p-1 text-muted-foreground hover:bg-muted">×</button></div><div className="mt-4 space-y-2">{[["01/07/2026","520.000 ₫/giờ","Đang hiệu lực"],["01/01/2026","480.000 ₫/giờ","Đã kết thúc"],["01/09/2025","430.000 ₫/giờ","Đã kết thúc"]].map(([date, rate, state], i) => <div key={date} className="flex items-center gap-3 rounded-lg border border-border p-3"><div className={`h-2 w-2 rounded-full ${i === 0 ? "bg-emerald-500" : "bg-slate-300"}`} /><div className="flex-1"><div className="text-xs font-semibold">{date}</div><div className="text-[11px] text-muted-foreground">Bắt đầu hiệu lực</div></div><span className="font-mono text-xs font-semibold">{rate}</span><Status tone={i === 0 ? "success" : "neutral"}>{state}</Status></div>)}</div><button onClick={() => setShowRate(false)} className="mt-5 h-10 w-full rounded-lg bg-primary text-xs font-bold text-white">Đóng</button></div></div> : null}
  </div></main></AppShell>;
}

function HoursBar({ label, value, max, color }: { label: string; value: number; max: number; color: string }) { return <div><div className="mb-1 flex justify-between text-[11px]"><span className="text-muted-foreground">{label}</span><span className="font-mono font-semibold">{value.toLocaleString("vi-VN")}h</span></div><div className="h-2 rounded-full bg-muted"><div className="h-full rounded-full" style={{ width: `${Math.min(100, (value / max) * 100)}%`, backgroundColor: color }} /></div></div>; }

export function PnlWorkbench() {
  const [projectId, setProjectId] = useState(PROJECTS[0].code);
  const [statusFilter, setStatusFilter] = useState("all");
  const [expanded, setExpanded] = useState(true);
  const visibleProjects = useMemo(() => PROJECTS.filter((item) => statusFilter === "all" || item.status === statusFilter), [statusFilter]);
  const project = visibleProjects.find((p) => p.code === projectId) ?? visibleProjects[0] ?? PROJECTS[0];
  const portfolio = useMemo(() => visibleProjects.reduce((total, item) => ({ plan: total.plan + item.plan, logwork: total.logwork + item.logwork, pnl: total.pnl + item.pnl, pending: total.pending + item.pending }), { plan: 0, logwork: 0, pnl: 0, pending: 0 }), [visibleProjects]);
  const excludedHours = Math.max(0, project.logwork - project.pnl - project.pending);
  const margin = project.revenue ? ((project.revenue - project.expenses) / project.revenue) * 100 : 0;
  return <AppShell activeRoute="/pnl" title="Project P&L"><main className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-[1480px] space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-primary">PROJECT P&L · PILOT</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">P&L theo Project</h1><p className="mt-1 text-xs text-muted-foreground">Đối soát Plan Hour, Logwork Hour, P&L Hour và chi phí nhân sự theo kỳ.</p></div><div className="flex flex-wrap items-center gap-2"><CustomDropdown ariaLabel="Kỳ báo cáo" options={[{ value: "2026-09", label: "Tháng 09/2026" }, { value: "2026-08", label: "Tháng 08/2026" }]} value="2026-09" onChange={() => {}} /><CustomDropdown ariaLabel="Trạng thái project" options={[{ value: "all", label: "Tất cả trạng thái" }, { value: "Active", label: "Active" }, { value: "In Review", label: "In Review" }, { value: "On Hold", label: "On Hold" }]} value={statusFilter} onChange={setStatusFilter} /><CustomDropdown ariaLabel="Chọn dự án" options={visibleProjects.map((p) => ({ value: p.code, label: `${p.code} · ${p.name}` }))} value={visibleProjects.some((p) => p.code === projectId) ? projectId : visibleProjects[0]?.code ?? projectId} onChange={setProjectId} /><button className="inline-flex h-10 items-center gap-2 rounded-lg border border-border px-3 text-xs font-semibold hover:bg-muted"><Download className="h-3.5 w-3.5" /> Xuất P&L</button></div></div>
    <div className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><span className="rounded-md bg-blue-50 px-2 py-1 font-mono text-[10px] font-bold text-blue-700">{project.code}</span><Status tone={project.status === "Active" ? "success" : project.status === "In Review" ? "info" : "warning"}>{project.status}</Status></div><h2 className="mt-2 text-lg font-bold">{project.name}</h2><p className="mt-1 text-xs text-muted-foreground">{project.client} · Kỳ báo cáo: Tháng 09/2026 · Cập nhật 13/09/2026 09:42</p></div><div className="flex items-center gap-2 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800"><Clock3 className="h-4 w-4" /> {project.pending.toLocaleString("vi-VN")}h đang chờ xử lý</div></div></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Plan Hour toàn bộ" value={`${portfolio.plan.toLocaleString("vi-VN")}h`} hint={`${PROJECTS.length} project trong kỳ`} icon={CalendarDays} /><Metric label="Logwork Hour toàn bộ" value={`${portfolio.logwork.toLocaleString("vi-VN")}h`} hint="Giờ đã ghi nhận" icon={Clock3} tone="green" /><Metric label="P&L Hour toàn bộ" value={`${portfolio.pnl.toLocaleString("vi-VN")}h`} hint={`${Math.round((portfolio.pnl / Math.max(1, portfolio.logwork)) * 100)}% Logwork đủ điều kiện`} icon={Check} tone="purple" /><Metric label="Chờ xử lý" value={`${portfolio.pending.toLocaleString("vi-VN")}h`} hint="Thiếu duyệt hoặc Cost Rate" icon={AlertTriangle} tone="amber" /></div>
    <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-xl border border-border bg-card p-4 shadow-sm"><h2 className="text-sm font-bold">1–2. Phạm vi project &amp; Revenue</h2><p className="mt-1 text-[11px] text-muted-foreground">Xác định đúng đối tượng doanh thu, effort và chi phí trong cùng phạm vi/kỳ.</p><dl className="mt-4 grid grid-cols-2 gap-x-5 gap-y-3 text-xs"><div><dt className="text-muted-foreground">Project / module</dt><dd className="mt-1 font-semibold">{project.name}</dd></div><div><dt className="text-muted-foreground">Client</dt><dd className="mt-1 font-semibold">{project.client}</dd></div><div><dt className="text-muted-foreground">Loại hợp đồng / dịch vụ</dt><dd className="mt-1 font-semibold">Fixed fee · Delivery</dd></div><div><dt className="text-muted-foreground">Kỳ báo cáo</dt><dd className="mt-1 font-semibold">Tháng 09/2026</dd></div><div><dt className="text-muted-foreground">Revenue chưa VAT</dt><dd className="mt-1 font-mono font-bold text-emerald-700">{project.revenue.toLocaleString("vi-VN")} ₫</dd></div><div><dt className="text-muted-foreground">Cơ sở ghi nhận</dt><dd className="mt-1 font-semibold">Doanh thu ghi nhận trong kỳ</dd></div></dl></section><section className="rounded-xl border border-border bg-card p-4 shadow-sm"><h2 className="text-sm font-bold">3. Effort kế hoạch</h2><p className="mt-1 text-[11px] text-muted-foreground">Baseline theo báo giá, hiển thị tách manday và giờ quy đổi.</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-blue-50 p-3"><span className="text-[10px] text-blue-700">Plan Hour</span><strong className="mt-1 block font-mono text-xl text-blue-800">{project.plan.toLocaleString("vi-VN")}h</strong></div><div className="rounded-lg bg-slate-100 p-3"><span className="text-[10px] text-slate-600">Plan Manday</span><strong className="mt-1 block font-mono text-xl text-slate-800">{(project.plan / 8).toLocaleString("vi-VN")} MD</strong></div></div><p className="mt-3 text-[11px] text-muted-foreground">Baseline không được gọi là Actual cho đến khi có Logwork được duyệt.</p></section></div>
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-bold">Thời gian theo từng Project</h2><p className="text-[11px] text-muted-foreground">{visibleProjects.length} project · Đối soát 3 lớp giờ: Plan → Logwork → P&amp;L.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Project</th><th className="px-3 py-3">Thời gian theo Plan</th><th className="px-3 py-3">Thời gian theo Logwork</th><th className="px-3 py-3">Thời gian P&amp;L</th><th className="px-3 py-3">Chênh lệch chờ xử lý</th><th className="px-3 py-3">Trạng thái</th></tr></thead><tbody className="divide-y divide-border">{visibleProjects.map((item) => <tr key={item.code} className={item.code === project.code ? "bg-blue-50/50" : ""}><td className="px-4 py-3"><div className="flex items-center gap-2"><span className="rounded-md bg-slate-100 px-2 py-1 font-mono text-[10px] font-bold text-slate-700">{item.code}</span><div><div className="font-semibold">{item.name}</div><div className="text-[10px] text-muted-foreground">{item.client}</div></div></div></td><td className="px-3 py-3"><div className="font-mono font-semibold">{item.plan.toLocaleString("vi-VN")}h</div><div className="mt-1 h-1.5 w-28 rounded-full bg-muted"><div className="h-full rounded-full bg-blue-500" style={{ width: "100%" }} /></div></td><td className="px-3 py-3"><div className="font-mono font-semibold">{item.logwork.toLocaleString("vi-VN")}h</div><div className="mt-1 h-1.5 w-28 rounded-full bg-muted"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.min(100, (item.logwork / Math.max(1, item.plan)) * 100)}%` }} /></div></td><td className="px-3 py-3"><div className="font-mono font-semibold">{item.pnl.toLocaleString("vi-VN")}h</div><div className="mt-1 h-1.5 w-28 rounded-full bg-muted"><div className="h-full rounded-full bg-violet-500" style={{ width: `${Math.min(100, (item.pnl / Math.max(1, item.plan)) * 100)}%` }} /></div></td><td className="px-3 py-3 font-mono font-semibold text-amber-700">{item.pending.toLocaleString("vi-VN")}h</td><td className="px-3 py-3"><Status tone={item.pending > 0 ? "warning" : "success"}>{item.pending > 0 ? "Cần đối soát" : "Đã khớp"}</Status></td></tr>)}</tbody></table></div></section>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Metric label="Revenue" value={`${(project.revenue / 1e9).toFixed(2)}B ₫`} hint="Doanh thu đã xác nhận" icon={WalletCards} /><Metric label="Total Expenses" value={`${(project.expenses / 1e6).toFixed(0)}M ₫`} hint={`${project.revenue ? ((project.expenses / project.revenue) * 100).toFixed(1) : "N/A"}% / Revenue`} icon={ArrowDownRight} tone="amber" /><Metric label="EBIT" value={project.revenue ? `${((project.revenue - project.expenses) / 1e6).toFixed(0)}M ₫` : "Thiếu dữ liệu"} hint={project.revenue ? `Biên EBIT ${margin.toFixed(1)}%` : "Chưa có Revenue xác nhận"} icon={ArrowUpRight} tone="green" /><Metric label="P&L Hour" value={`${project.pnl.toLocaleString("vi-VN")}h`} hint="Đủ điều kiện tính chi phí" icon={Clock3} tone="purple" /><Metric label="Logwork Hour" value={`${project.logwork.toLocaleString("vi-VN")}h`} hint="Tổng giờ thực tế đã ghi" icon={CalendarDays} /></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(340px,.8fr)]"><section className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">Ba lớp giờ & đối soát</h2><p className="text-[11px] text-muted-foreground">P&L Hour + Bị loại + Chờ xử lý = Logwork Hour</p></div><Status tone={project.pnl + excludedHours + project.pending === project.logwork ? "success" : "danger"}><Check className="h-3 w-3" /> {project.pnl + excludedHours + project.pending === project.logwork ? "Khớp số liệu" : "Lệch số liệu"}</Status></div><div className="mt-5 space-y-4"><HoursBar label="Plan Hour" value={project.plan} max={project.plan} color="#2563eb" /><HoursBar label="Logwork Hour" value={project.logwork} max={project.plan} color="#10b981" /><HoursBar label="P&L Hour" value={project.pnl} max={project.plan} color="#8b5cf6" /></div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-lg bg-emerald-50 p-3"><span className="block text-[10px] text-emerald-700">Được tính</span><strong className="mt-1 block font-mono text-lg text-emerald-800">{project.pnl}h</strong></div><div className="rounded-lg bg-slate-100 p-3"><span className="block text-[10px] text-slate-600">Bị loại</span><strong className="mt-1 block font-mono text-lg text-slate-800">{excludedHours}h</strong></div><div className="rounded-lg bg-amber-50 p-3"><span className="block text-[10px] text-amber-700">Chờ xử lý</span><strong className="mt-1 block font-mono text-lg text-amber-800">{project.pending}h</strong></div></div></section><section className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">Worklog Daily</h2><p className="text-[11px] text-muted-foreground">Theo nhân sự và nhóm công việc</p></div><button className="text-xs font-semibold text-primary">Xem Time Log</button></div><div className="mt-4 space-y-3">{PEOPLE.slice(0,4).map((person, i) => <div key={person.id} className="flex items-center gap-2"><Avatar person={person} /><div className="min-w-0 flex-1"><div className="flex justify-between text-xs"><span className="truncate font-semibold">{person.name}</span><span className="font-mono">{[640,520,480,360][i]}h</span></div><div className="mt-1 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-blue-500" style={{ width: `${[88,72,66,52][i]}%` }} /></div></div></div>)}</div></section></div>
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><button onClick={() => setExpanded(!expanded)} className="flex w-full items-center justify-between border-b border-border px-4 py-3 text-left hover:bg-muted/30"><div><h2 className="text-sm font-bold">Chi phí nhân sự & ngoại lệ</h2><p className="text-[11px] text-muted-foreground">Cost Rate được lấy theo ngày ghi giờ</p></div>{expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</button>{expanded ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Nhân sự</th><th className="px-3 py-3">Nhóm công việc</th><th className="px-3 py-3">P&L Hour</th><th className="px-3 py-3">Cost Rate</th><th className="px-3 py-3">Labor Cost</th><th className="px-3 py-3">Trạng thái</th></tr></thead><tbody className="divide-y divide-border">{PEOPLE.slice(0,4).map((person, i) => <tr key={person.id}><td className="px-4 py-3"><div className="flex items-center gap-2"><Avatar person={person} /><span className="font-semibold">{person.name}</span></div></td><td className="px-3 py-3 text-muted-foreground">{i === 0 ? "PM · Project khách hàng" : i === 1 ? "Delivery · Project khách hàng" : "Delivery · Project khách hàng"}</td><td className="px-3 py-3 font-mono font-semibold">{[640, 520, 480, 360][i]}h</td><td className="px-3 py-3 font-mono">{person.rate.toLocaleString("vi-VN")} ₫</td><td className="px-3 py-3 font-mono font-semibold">{([640, 520, 480, 360][i] * person.rate).toLocaleString("vi-VN")} ₫</td><td className="px-3 py-3"><Status tone="success">Đã tính</Status></td></tr>)}<tr className="bg-muted/30 font-bold"><td className="px-4 py-3" colSpan={2}>Tổng chi phí nhân sự</td><td className="px-3 py-3 font-mono">{project.pnl}h</td><td /><td className="px-3 py-3 font-mono">{project.expenses.toLocaleString("vi-VN")} ₫</td><td /></tr></tbody></table></div> : null}</section>
    <section className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">5. Expenses theo 6 nhóm</h2><p className="text-[11px] text-muted-foreground">BD, PM, Delivery/DX, AI/công cụ, Overhead và nhóm khác.</p></div><span className="font-mono text-sm font-bold">{project.expenses.toLocaleString("vi-VN")} ₫</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{EXPENSE_GROUPS.map((group) => <div key={group.label} className="rounded-lg border border-border p-3"><div className="flex justify-between text-xs"><span className="font-semibold">{group.label}</span><span className="font-mono">{Math.round(group.share * 100)}%</span></div><div className="mt-2 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-amber-500" style={{ width: `${group.share * 100}%` }} /></div><div className="mt-2 font-mono text-xs font-semibold">{Math.round(project.expenses * group.share).toLocaleString("vi-VN")} ₫</div></div>)}</div></section>
    <div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" /><div className="min-w-0"><h2 className="text-xs font-bold text-amber-900">Đối soát & danh sách chờ xử lý</h2><p className="mt-1 text-[11px] leading-relaxed text-amber-800">{project.pending}h chưa được đưa vào P&L Hour vì thiếu xác nhận hoặc Cost Rate hiệu lực. Mở danh sách ngoại lệ để xử lý từng Time Log và lưu người thao tác/lý do.</p></div><button className="ml-auto shrink-0 rounded-lg border border-amber-300 bg-white px-3 py-2 text-[11px] font-bold text-amber-800 hover:bg-amber-100">Mở ngoại lệ</button></div></div>
  </div></main></AppShell>;
}
