-- Expand SaaS tenant/workspace boundary to the remaining core operational records.
-- The migration is additive first, then backfills each child record from its owning aggregate.

ALTER TABLE "Lead" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "AccountMember" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "AccountUsageReview" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "Opportunity" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProposalPackage" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProposalDocument" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "DealApprovalRequest" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "DealApprovalDecision" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "Contract" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ContractDocument" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "PaymentSchedule" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "PaymentMilestone" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "Invoice" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "InvoicePayment" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ArFollowUp" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "PaymentEvidence" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "OpportunityActivity" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "OpportunityStageHistory" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ResourceAllocation" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectBudget" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectCost" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectPlSnapshot" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "Ticket" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "TicketStatusHistory" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectArtifact" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "FileObject" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "FileDownloadGrant" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectMember" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "TaskComment" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectComment" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "TaskAttachment" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectAttachment" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "TaskStatusHistory" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "TaskTimeEntry" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "CustomerAccessGrant" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "PortalInvitation" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "ProjectProgressShareLink" ADD COLUMN "workspaceId" TEXT NOT NULL DEFAULT 'twk-foundation';
ALTER TABLE "PolicyDecisionLog" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "IntegrationEventLog" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "AuditEvent" ADD COLUMN "workspaceId" TEXT;

UPDATE "AccountMember" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "AccountUsageReview" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "Lead" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "Opportunity" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "ProposalPackage" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "ProposalDocument" x SET "workspaceId" = p."workspaceId" FROM "ProposalPackage" p WHERE x."proposalPackageId" = p."id";
UPDATE "DealApprovalRequest" x SET "workspaceId" = p."workspaceId" FROM "ProposalPackage" p WHERE x."proposalPackageId" = p."id";
UPDATE "DealApprovalDecision" x SET "workspaceId" = r."workspaceId" FROM "DealApprovalRequest" r WHERE x."approvalRequestId" = r."id";
UPDATE "Contract" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "ContractDocument" x SET "workspaceId" = c."workspaceId" FROM "Contract" c WHERE x."contractId" = c."id";
UPDATE "PaymentSchedule" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "PaymentMilestone" x SET "workspaceId" = s."workspaceId" FROM "PaymentSchedule" s WHERE x."scheduleId" = s."id";
UPDATE "Invoice" x SET "workspaceId" = m."workspaceId" FROM "PaymentMilestone" m WHERE x."milestoneId" = m."id";
UPDATE "InvoicePayment" x SET "workspaceId" = i."workspaceId" FROM "Invoice" i WHERE x."invoiceId" = i."id";
UPDATE "ArFollowUp" x SET "workspaceId" = m."workspaceId" FROM "PaymentMilestone" m WHERE x."milestoneId" = m."id";
UPDATE "PaymentEvidence" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "OpportunityActivity" x SET "workspaceId" = o."workspaceId" FROM "Opportunity" o WHERE x."opportunityId" = o."id";
UPDATE "OpportunityStageHistory" x SET "workspaceId" = o."workspaceId" FROM "Opportunity" o WHERE x."opportunityId" = o."id";
UPDATE "ResourceAllocation" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "ProjectBudget" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";
UPDATE "ProjectCost" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";
UPDATE "ProjectPlSnapshot" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";
UPDATE "Ticket" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "TicketStatusHistory" x SET "workspaceId" = t."workspaceId" FROM "Ticket" t WHERE x."ticketId" = t."id";
UPDATE "ProjectArtifact" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "FileObject" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "FileDownloadGrant" x SET "workspaceId" = f."workspaceId" FROM "FileObject" f WHERE x."fileObjectId" = f."id";
UPDATE "ProjectMember" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";
UPDATE "TaskComment" x SET "workspaceId" = t."workspaceId" FROM "ProjectTask" t WHERE x."taskId" = t."id";
UPDATE "ProjectComment" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";
UPDATE "TaskAttachment" x SET "workspaceId" = t."workspaceId" FROM "ProjectTask" t WHERE x."taskId" = t."id";
UPDATE "ProjectAttachment" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";
UPDATE "TaskStatusHistory" x SET "workspaceId" = t."workspaceId" FROM "ProjectTask" t WHERE x."taskId" = t."id";
UPDATE "TaskTimeEntry" x SET "workspaceId" = t."workspaceId" FROM "ProjectTask" t WHERE x."taskId" = t."id";
UPDATE "CustomerAccessGrant" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "CustomerAccessGrant" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id" AND x."accountId" IS NULL;
UPDATE "PortalInvitation" x SET "workspaceId" = a."workspaceId" FROM "Account" a WHERE x."accountId" = a."id";
UPDATE "PortalInvitation" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id" AND x."accountId" IS NULL;
UPDATE "ProjectProgressShareLink" x SET "workspaceId" = p."workspaceId" FROM "Project" p WHERE x."projectId" = p."id";

DROP INDEX IF EXISTS "AccountMember_accountId_userId_relation_key";
DROP INDEX IF EXISTS "ProjectMember_projectId_userId_relation_key";
DROP INDEX IF EXISTS "Opportunity_accountId_title_key";
DROP INDEX IF EXISTS "ProposalPackage_opportunityId_version_key";
DROP INDEX IF EXISTS "ProposalDocument_proposalPackageId_documentType_version_key";
DROP INDEX IF EXISTS "DealApprovalRequest_proposalPackageId_requestType_requiredRoleCode_key";
DROP INDEX IF EXISTS "ContractDocument_contractId_documentType_version_key";
DROP INDEX IF EXISTS "PaymentMilestone_scheduleId_sequence_key";

CREATE UNIQUE INDEX "AccountMember_workspaceId_accountId_userId_relation_key" ON "AccountMember"("workspaceId", "accountId", "userId", "relation");
CREATE INDEX "AccountMember_workspaceId_userId_idx" ON "AccountMember"("workspaceId", "userId");
CREATE INDEX "AccountUsageReview_workspaceId_accountId_month_idx" ON "AccountUsageReview"("workspaceId", "accountId", "month");
CREATE UNIQUE INDEX "Opportunity_workspaceId_accountId_title_key" ON "Opportunity"("workspaceId", "accountId", "title");
CREATE UNIQUE INDEX "ProposalPackage_workspaceId_opportunityId_version_key" ON "ProposalPackage"("workspaceId", "opportunityId", "version");
CREATE UNIQUE INDEX "ProposalDocument_workspaceId_proposalPackageId_documentType_version_key" ON "ProposalDocument"("workspaceId", "proposalPackageId", "documentType", "version");
CREATE UNIQUE INDEX "DealApprovalRequest_workspaceId_proposalPackageId_requestType_requiredRoleCode_key" ON "DealApprovalRequest"("workspaceId", "proposalPackageId", "requestType", "requiredRoleCode");
CREATE UNIQUE INDEX "ContractDocument_workspaceId_contractId_documentType_version_key" ON "ContractDocument"("workspaceId", "contractId", "documentType", "version");
CREATE UNIQUE INDEX "PaymentMilestone_workspaceId_scheduleId_sequence_key" ON "PaymentMilestone"("workspaceId", "scheduleId", "sequence");

CREATE INDEX "Lead_workspaceId_status_idx" ON "Lead"("workspaceId", "status");
CREATE INDEX "Opportunity_workspaceId_stage_idx" ON "Opportunity"("workspaceId", "stage");
CREATE INDEX "ProposalPackage_workspaceId_status_idx" ON "ProposalPackage"("workspaceId", "status");
CREATE INDEX "ProposalDocument_workspaceId_documentType_idx" ON "ProposalDocument"("workspaceId", "documentType");
CREATE INDEX "DealApprovalRequest_workspaceId_status_idx" ON "DealApprovalRequest"("workspaceId", "status");
CREATE INDEX "DealApprovalDecision_workspaceId_decision_idx" ON "DealApprovalDecision"("workspaceId", "decision");
CREATE INDEX "Contract_workspaceId_status_idx" ON "Contract"("workspaceId", "status");
CREATE INDEX "ContractDocument_workspaceId_documentType_idx" ON "ContractDocument"("workspaceId", "documentType");
CREATE INDEX "PaymentSchedule_workspaceId_status_idx" ON "PaymentSchedule"("workspaceId", "status");
CREATE INDEX "PaymentMilestone_workspaceId_status_idx" ON "PaymentMilestone"("workspaceId", "status");
CREATE INDEX "Invoice_workspaceId_paymentStatus_idx" ON "Invoice"("workspaceId", "paymentStatus");
CREATE INDEX "InvoicePayment_workspaceId_paidAt_idx" ON "InvoicePayment"("workspaceId", "paidAt");
CREATE INDEX "ArFollowUp_workspaceId_status_idx" ON "ArFollowUp"("workspaceId", "status");
CREATE INDEX "PaymentEvidence_workspaceId_evidenceType_idx" ON "PaymentEvidence"("workspaceId", "evidenceType");
CREATE INDEX "OpportunityActivity_workspaceId_status_idx" ON "OpportunityActivity"("workspaceId", "status");
CREATE INDEX "OpportunityStageHistory_workspaceId_changedAt_idx" ON "OpportunityStageHistory"("workspaceId", "changedAt");
CREATE INDEX "ResourceAllocation_workspaceId_status_idx" ON "ResourceAllocation"("workspaceId", "status");
CREATE INDEX "ProjectBudget_workspaceId_status_idx" ON "ProjectBudget"("workspaceId", "status");
CREATE INDEX "ProjectCost_workspaceId_occurredAt_idx" ON "ProjectCost"("workspaceId", "occurredAt");
CREATE INDEX "ProjectPlSnapshot_workspaceId_periodStart_periodEnd_idx" ON "ProjectPlSnapshot"("workspaceId", "periodStart", "periodEnd");
CREATE INDEX "Ticket_workspaceId_status_idx" ON "Ticket"("workspaceId", "status");
CREATE INDEX "TicketStatusHistory_workspaceId_createdAt_idx" ON "TicketStatusHistory"("workspaceId", "createdAt");
CREATE INDEX "ProjectArtifact_workspaceId_artifactType_idx" ON "ProjectArtifact"("workspaceId", "artifactType");
CREATE INDEX "FileObject_workspaceId_status_idx" ON "FileObject"("workspaceId", "status");
CREATE INDEX "FileDownloadGrant_workspaceId_expiresAt_idx" ON "FileDownloadGrant"("workspaceId", "expiresAt");
CREATE UNIQUE INDEX "ProjectMember_workspaceId_projectId_userId_relation_key" ON "ProjectMember"("workspaceId", "projectId", "userId", "relation");
CREATE INDEX "ProjectMember_workspaceId_userId_idx" ON "ProjectMember"("workspaceId", "userId");
CREATE INDEX "TaskComment_workspaceId_createdAt_idx" ON "TaskComment"("workspaceId", "createdAt");
CREATE INDEX "ProjectComment_workspaceId_createdAt_idx" ON "ProjectComment"("workspaceId", "createdAt");
CREATE INDEX "TaskAttachment_workspaceId_createdAt_idx" ON "TaskAttachment"("workspaceId", "createdAt");
CREATE INDEX "ProjectAttachment_workspaceId_createdAt_idx" ON "ProjectAttachment"("workspaceId", "createdAt");
CREATE INDEX "TaskStatusHistory_workspaceId_changedAt_idx" ON "TaskStatusHistory"("workspaceId", "changedAt");
CREATE INDEX "TaskTimeEntry_workspaceId_workDate_idx" ON "TaskTimeEntry"("workspaceId", "workDate");
CREATE INDEX "CustomerAccessGrant_workspaceId_idx" ON "CustomerAccessGrant"("workspaceId");
CREATE INDEX "PortalInvitation_workspaceId_status_idx" ON "PortalInvitation"("workspaceId", "status");
CREATE INDEX "ProjectProgressShareLink_workspaceId_idx" ON "ProjectProgressShareLink"("workspaceId");
CREATE INDEX "PolicyDecisionLog_workspaceId_createdAt_idx" ON "PolicyDecisionLog"("workspaceId", "createdAt");
CREATE INDEX "IntegrationEventLog_workspaceId_status_idx" ON "IntegrationEventLog"("workspaceId", "status");
CREATE INDEX "AuditEvent_workspaceId_createdAt_idx" ON "AuditEvent"("workspaceId", "createdAt");

ALTER TABLE "AccountMember" ADD CONSTRAINT "AccountMember_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AccountUsageReview" ADD CONSTRAINT "AccountUsageReview_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProposalPackage" ADD CONSTRAINT "ProposalPackage_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProposalDocument" ADD CONSTRAINT "ProposalDocument_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DealApprovalRequest" ADD CONSTRAINT "DealApprovalRequest_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DealApprovalDecision" ADD CONSTRAINT "DealApprovalDecision_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Contract" ADD CONSTRAINT "Contract_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ContractDocument" ADD CONSTRAINT "ContractDocument_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentSchedule" ADD CONSTRAINT "PaymentSchedule_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentMilestone" ADD CONSTRAINT "PaymentMilestone_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InvoicePayment" ADD CONSTRAINT "InvoicePayment_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ArFollowUp" ADD CONSTRAINT "ArFollowUp_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentEvidence" ADD CONSTRAINT "PaymentEvidence_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OpportunityActivity" ADD CONSTRAINT "OpportunityActivity_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OpportunityStageHistory" ADD CONSTRAINT "OpportunityStageHistory_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ResourceAllocation" ADD CONSTRAINT "ResourceAllocation_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectBudget" ADD CONSTRAINT "ProjectBudget_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectCost" ADD CONSTRAINT "ProjectCost_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectPlSnapshot" ADD CONSTRAINT "ProjectPlSnapshot_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketStatusHistory" ADD CONSTRAINT "TicketStatusHistory_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectArtifact" ADD CONSTRAINT "ProjectArtifact_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FileObject" ADD CONSTRAINT "FileObject_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FileDownloadGrant" ADD CONSTRAINT "FileDownloadGrant_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectMember" ADD CONSTRAINT "ProjectMember_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskComment" ADD CONSTRAINT "TaskComment_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectComment" ADD CONSTRAINT "ProjectComment_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskAttachment" ADD CONSTRAINT "TaskAttachment_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectAttachment" ADD CONSTRAINT "ProjectAttachment_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskStatusHistory" ADD CONSTRAINT "TaskStatusHistory_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskTimeEntry" ADD CONSTRAINT "TaskTimeEntry_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CustomerAccessGrant" ADD CONSTRAINT "CustomerAccessGrant_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PortalInvitation" ADD CONSTRAINT "PortalInvitation_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectProgressShareLink" ADD CONSTRAINT "ProjectProgressShareLink_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PolicyDecisionLog" ADD CONSTRAINT "PolicyDecisionLog_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IntegrationEventLog" ADD CONSTRAINT "IntegrationEventLog_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TenantWorkspace"("id") ON DELETE SET NULL ON UPDATE CASCADE;
