import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const { jar } = vi.hoisted(() => ({ jar: new Map<string,string>() }));
vi.mock("next/headers", () => ({ cookies: async () => ({ get: (name:string) => jar.has(name) ? {value:jar.get(name)} : undefined }) }));
import { proxyNativeAuth } from "./native-auth-proxy";
beforeEach(()=>{jar.clear();vi.stubEnv("PUBLIC_WEB_URL","http://localhost:3000");vi.stubEnv("CRM_API_INTERNAL_URL","http://localhost:4000");});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
const request=(body:unknown={},origin="http://localhost:3000")=>new Request("http://localhost:3000/api/auth/native/password/login",{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify(body)});
describe("native auth cookie adapter",()=>{
 it("rejects cross-site login before calling the authentication service",async()=>{const fetcher=vi.fn();vi.stubGlobal("fetch",fetcher);const r=await proxyNativeAuth(request({},"https://other.test"),"password/login");expect(r.status).toBe(403);expect(fetcher).not.toHaveBeenCalled();});
 it("keeps successful bearer session in HttpOnly cookie and out of JSON",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({token:"private-session",expiresAt:"2026-12-31T00:00:00Z",principal:{subjectId:"user"}})));const r=await proxyNativeAuth(request({email:"a@example.test",password:"secret"}),"password/login");expect(await r.json()).toEqual({expiresAt:"2026-12-31T00:00:00Z",principal:{subjectId:"user"}});expect(r.headers.get("set-cookie")).toContain("lcrm_session=private-session");expect(r.headers.get("set-cookie")).toContain("HttpOnly");});
 it("holds MFA challenge in HttpOnly cookie and trusts it instead of browser body",async()=>{let fetcher=vi.fn().mockResolvedValue(Response.json({mfaRequired:true,challengeToken:"private-challenge",expiresAt:"2026-12-31T00:00:00Z"}));vi.stubGlobal("fetch",fetcher);const r=await proxyNativeAuth(request({}),"password/login");expect((await r.json()).challengeToken).toBeUndefined();expect(r.headers.get("set-cookie")).toContain("lcrm_mfa_challenge=private-challenge");jar.set("lcrm_mfa_challenge","cookie-challenge");fetcher=vi.fn().mockResolvedValue(Response.json({message:"Invalid"},{status:401}));vi.stubGlobal("fetch",fetcher);await proxyNativeAuth(request({challengeToken:"attacker-input",code:"123456"}),"mfa/challenge");expect(JSON.parse(fetcher.mock.calls[0][1].body).challengeToken).toBe("cookie-challenge");});
 it("expires browser session after security changes request reauthentication",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({changed:true,signInRequired:true})));const r=await proxyNativeAuth(request({}),"password/change");expect(r.headers.get("set-cookie")).toContain("Max-Age=0");});
});
